services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UID: 1000
        GID: 1000
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public

  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: chamados
      MARIADB_USER: root
      MARIADB_PASSWORD: root
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - db
  
  node:
    image: node:20
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: tail -f /dev/null
    tty: true
    ports:
      - "5173:5173"
    # profiles: ["tools"]
volumes:
  dbdata:
